--------------------------------------------------------
--  File created - Thursday-May-16-2024   
--------------------------------------------------------
--------------------------------------------------------
--  DDL for Table CONTACT
--------------------------------------------------------

  CREATE TABLE "EVERGREEN"."CONTACT" 
   (	"CONTACT_ID" NUMBER, 
	"CUSTOMER_NAME" VARCHAR2(255 BYTE), 
	"ADDRESS" VARCHAR2(255 BYTE), 
	"CUSTOMER_CONCERN" VARCHAR2(255 BYTE), 
	"CUSTOMER_COMMENT" VARCHAR2(255 BYTE), 
	"GENDER" VARCHAR2(20 BYTE)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Table CUSTOMER
--------------------------------------------------------

  CREATE TABLE "EVERGREEN"."CUSTOMER" 
   (	"USER_ID" NUMBER, 
	"USER_NAME" VARCHAR2(20 BYTE), 
	"PASSWORD" VARCHAR2(20 BYTE)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Table PRODUCT
--------------------------------------------------------

  CREATE TABLE "EVERGREEN"."PRODUCT" 
   (	"PRODUCT_ID" NUMBER, 
	"PRODUCT_NAME" VARCHAR2(100 BYTE), 
	"IMAGE_LINK" VARCHAR2(100 BYTE), 
	"AMOUNT" NUMBER
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Table TRANSACTION
--------------------------------------------------------

  CREATE TABLE "EVERGREEN"."TRANSACTION" 
   (	"TRANSACTION_ID" NUMBER, 
	"USER_ID" NUMBER, 
	"PRODUCT_ID" NUMBER, 
	"TRANSACTION_DATE" DATE
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
REM INSERTING into EVERGREEN.CONTACT
SET DEFINE OFF;
Insert into EVERGREEN.CONTACT (CONTACT_ID,CUSTOMER_NAME,ADDRESS,CUSTOMER_CONCERN,CUSTOMER_COMMENT,GENDER) values (41,'Ivan Ren Villamora','Blk. 12 Lot 19 Caloocan City','Learn More','I want to learn more','Male');
Insert into EVERGREEN.CONTACT (CONTACT_ID,CUSTOMER_NAME,ADDRESS,CUSTOMER_CONCERN,CUSTOMER_COMMENT,GENDER) values (22,'Ivan Ren Villamora','caloocan city','Failed Transaction','Order failed','Male');
REM INSERTING into EVERGREEN.CUSTOMER
SET DEFINE OFF;
Insert into EVERGREEN.CUSTOMER (USER_ID,USER_NAME,PASSWORD) values (61,'john','john');
Insert into EVERGREEN.CUSTOMER (USER_ID,USER_NAME,PASSWORD) values (22,'ivanren','ivanren');
Insert into EVERGREEN.CUSTOMER (USER_ID,USER_NAME,PASSWORD) values (23,'patrick','patrick');
Insert into EVERGREEN.CUSTOMER (USER_ID,USER_NAME,PASSWORD) values (41,'viamallari','via12345');
REM INSERTING into EVERGREEN.PRODUCT
SET DEFINE OFF;
Insert into EVERGREEN.PRODUCT (PRODUCT_ID,PRODUCT_NAME,IMAGE_LINK,AMOUNT) values (61,'Daisy','/Items/20240515213650daisy.jpg',900);
Insert into EVERGREEN.PRODUCT (PRODUCT_ID,PRODUCT_NAME,IMAGE_LINK,AMOUNT) values (41,'Rose','/Items/20240514093704single-red-rose.jpg',5000);
Insert into EVERGREEN.PRODUCT (PRODUCT_ID,PRODUCT_NAME,IMAGE_LINK,AMOUNT) values (22,'Sunflower','/Items/20240506090430sunflower.jpg',6000);
Insert into EVERGREEN.PRODUCT (PRODUCT_ID,PRODUCT_NAME,IMAGE_LINK,AMOUNT) values (23,'Lily','/Items/20240506090631lily.jpg',900);
REM INSERTING into EVERGREEN.TRANSACTION
SET DEFINE OFF;
Insert into EVERGREEN.TRANSACTION (TRANSACTION_ID,USER_ID,PRODUCT_ID,TRANSACTION_DATE) values (61,61,41,to_date('15-MAY-24','DD-MON-RR'));
Insert into EVERGREEN.TRANSACTION (TRANSACTION_ID,USER_ID,PRODUCT_ID,TRANSACTION_DATE) values (26,22,22,to_date('06-MAY-24','DD-MON-RR'));
Insert into EVERGREEN.TRANSACTION (TRANSACTION_ID,USER_ID,PRODUCT_ID,TRANSACTION_DATE) values (27,23,23,to_date('06-MAY-24','DD-MON-RR'));
Insert into EVERGREEN.TRANSACTION (TRANSACTION_ID,USER_ID,PRODUCT_ID,TRANSACTION_DATE) values (28,23,22,to_date('06-MAY-24','DD-MON-RR'));
--------------------------------------------------------
--  DDL for Index SYS_C008321
--------------------------------------------------------

  CREATE UNIQUE INDEX "EVERGREEN"."SYS_C008321" ON "EVERGREEN"."CONTACT" ("CONTACT_ID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Index CUSTOMER_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "EVERGREEN"."CUSTOMER_PK" ON "EVERGREEN"."CUSTOMER" ("USER_ID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Index PRODUCT_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "EVERGREEN"."PRODUCT_PK" ON "EVERGREEN"."PRODUCT" ("PRODUCT_ID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Index SYS_C008330
--------------------------------------------------------

  CREATE UNIQUE INDEX "EVERGREEN"."SYS_C008330" ON "EVERGREEN"."TRANSACTION" ("TRANSACTION_ID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  Constraints for Table CONTACT
--------------------------------------------------------

  ALTER TABLE "EVERGREEN"."CONTACT" ADD PRIMARY KEY ("CONTACT_ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS"  ENABLE;
--------------------------------------------------------
--  Constraints for Table CUSTOMER
--------------------------------------------------------

  ALTER TABLE "EVERGREEN"."CUSTOMER" MODIFY ("USER_ID" NOT NULL ENABLE);
  ALTER TABLE "EVERGREEN"."CUSTOMER" MODIFY ("USER_NAME" NOT NULL ENABLE);
  ALTER TABLE "EVERGREEN"."CUSTOMER" MODIFY ("PASSWORD" NOT NULL ENABLE);
  ALTER TABLE "EVERGREEN"."CUSTOMER" ADD CONSTRAINT "CUSTOMER_PK" PRIMARY KEY ("USER_ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS"  ENABLE;
--------------------------------------------------------
--  Constraints for Table PRODUCT
--------------------------------------------------------

  ALTER TABLE "EVERGREEN"."PRODUCT" MODIFY ("PRODUCT_ID" NOT NULL ENABLE);
  ALTER TABLE "EVERGREEN"."PRODUCT" MODIFY ("PRODUCT_NAME" NOT NULL ENABLE);
  ALTER TABLE "EVERGREEN"."PRODUCT" MODIFY ("IMAGE_LINK" NOT NULL ENABLE);
  ALTER TABLE "EVERGREEN"."PRODUCT" MODIFY ("AMOUNT" NOT NULL ENABLE);
  ALTER TABLE "EVERGREEN"."PRODUCT" ADD CONSTRAINT "PRODUCT_PK" PRIMARY KEY ("PRODUCT_ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS"  ENABLE;
--------------------------------------------------------
--  Constraints for Table TRANSACTION
--------------------------------------------------------

  ALTER TABLE "EVERGREEN"."TRANSACTION" ADD PRIMARY KEY ("TRANSACTION_ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS"  ENABLE;
--------------------------------------------------------
--  Ref Constraints for Table TRANSACTION
--------------------------------------------------------

  ALTER TABLE "EVERGREEN"."TRANSACTION" ADD FOREIGN KEY ("USER_ID")
	  REFERENCES "EVERGREEN"."CUSTOMER" ("USER_ID") ENABLE;
  ALTER TABLE "EVERGREEN"."TRANSACTION" ADD FOREIGN KEY ("PRODUCT_ID")
	  REFERENCES "EVERGREEN"."PRODUCT" ("PRODUCT_ID") ENABLE;
